### ISSUE TITLE
High Density Form Header

### ISSUE THREAD

**Issue by sabharwalvarun** [ORBISAG/ORBIS.PCF.ColorfulOptionset#4] opened 2020-04-10 23:10 UTC
Thank you for taking time and providing this component!

I tried using it on a High Density Form Header and the Control just disappears. Would be great if you could throw some light on what could be causing that.

Thanks
Varun

**Comment by brasov2de** [comment] 2020-04-13 09:07
HI Varun,
Thanks for pointing out the issue. In my opinion it's a bug in the Dynamics 365.
I've reported it in the community: https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Bug-PCF-inside-High-Density-Form-Header-not-displayed/m-p/524028#M2138
Let's see if  this will be fixed.
Best regards,
Diana

**Comment by brasov2de** [comment] 2020-04-15 08:39
Hi Varun,
It seems that the PCF doesn't work in High Density Headers by design, as Microsoft answered. I wasn't aware of that.

> To ensure that key information is always visible, the framework displays read-only field values and users can't directly edit the field values in the header. Visualizations such as **custom components or web resources also aren't allowed.**

https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Bug-PCF-inside-High-Density-Form-Header-not-displayed/m-p/524809#M2141

**Closed as completed by brasov2de** 2020-04-15 08:39 UTC
